-- "Whose phone is this?" — a free-text provenance label captured on the confirm screen,
-- before the QR is shown.
--
-- WHY A TYPED LABEL AND NOT A MEASURED VALUE: the android and ios paths hand the tenant a
-- QR that opens an UNAUTHENTICATED page; the device never identifies itself and no phone
-- number is transmitted or knowable. Only the WhatsApp path observes a real number, and it
-- already has a column for it (wa_phone). A typed label is therefore the only provenance
-- that works on all three paths — and it must be treated as an assertion, never as proof.
--
-- WHY NOT REUSE created_by_user_id: that records who CLICKED, which is routinely not whose
-- phone was scanned. An owner minting a QR for the shop manager's handset is the ordinary
-- case, not the edge one. Collapsing the two would manufacture a confident wrong answer.
--
-- Additive and nullable with no default, so this is a catalog-only change on PG11+ — no
-- table rewrite, no long lock. contact_sync_sessions is small and cold anyway; the same
-- shape on `contacts` would not have been free, which is why the durable half of this
-- feature rides on contact_tags instead of a new column there.
--
-- No RLS work: contact_sync_sessions already carries a per-row tenant_isolation policy
-- (migration 20260731120500 + rls.sql), and a policy covers every column of its table,
-- including ones added later.
--
-- Nothing to backfill. Sessions that predate this stay NULL, which is the honest value:
-- nobody was ever asked. The UI renders NULL as "Not recorded".
ALTER TABLE "contact_sync_sessions"
  ADD COLUMN IF NOT EXISTS "synced_by_label" TEXT;
