-- When the contacts actually LANDED, as opposed to when the QR was minted.
--
-- WHY. The undo window, the "recent syncs" list and the reaper's prune all measured from
-- created_at — the moment the QR appeared on screen. But a STAGED run (anything over 50
-- contacts, or any attested run) sits in review until a human comes back to it, and that can
-- be days. So a tenant who reviewed a big iPhone export for five days and then imported it
-- was told "can be undone for 7 days" while actually holding two, and the reaper would delete
-- the ledger recording what to undo the day after. The promise on screen was false by exactly
-- however long the review took, and it failed silently: the Undo button simply stopped
-- appearing.
--
-- created_at cannot be reused for this and updated_at cannot either — @updatedAt moves on
-- every write, including the label correction and the reaper's own sweeps, so the window
-- would quietly extend itself every time anything touched the row.
--
-- NULL means "imported before this column existed" (or never imported at all). Every reader
-- falls back to created_at for those, which preserves exactly today's behaviour for existing
-- rows — nothing already in flight gets a shorter or longer window than it was promised.
-- Deliberately NOT backfilled to created_at: that would be indistinguishable from a genuine
-- import timestamp, and the distinction is the point.
--
-- Additive, nullable, no default: catalog-only on PG11+, no rewrite. No RLS work —
-- contact_sync_sessions already carries a per-row tenant_isolation policy, and a policy
-- covers every column of its table including ones added later.
ALTER TABLE "contact_sync_sessions"
  ADD COLUMN IF NOT EXISTS "imported_at" TIMESTAMP(3);
